# Generated by Django 5.2 on 2025-04-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
